"""PITBULL Auto-Report Generator — mission reports with academic citations.

Generates professional reports from exploration data with:
- Executive summary
- Findings by severity
- ATT&CK technique mapping
- Infrastructure analysis
- Academic citations
- PITBULL personality snapshot

Academic basis:
- Spoor (2026): audit trail for forensic integrity
- PTFusion (Information Fusion 2026): knowledge fusion for reporting
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime
from typing import Any

from app.core.database import cypher_read
from app.api.personality import _load_state
from app.core.attack import attack_framework

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates professional exploration reports."""

    def generate_mission_report(self, target: str) -> dict[str, Any]:
        """Generate a comprehensive exploration report for a target."""
        report_id = str(uuid.uuid4())[:12]
        timestamp = datetime.now().isoformat()

        # Gather all data
        stats = cypher_read("MATCH (d:Domain {hostname: $target})-[:HAS_SUBDOMAIN]->(s:Subdomain) RETURN count(s) AS sub_count", {"target": target})
        ips = cypher_read("MATCH (d:Domain {hostname: $target})-[:RESOLVES_TO]->(i:IPAddress) RETURN collect(i.ip) AS ips", {"target": target})
        certs = cypher_read("MATCH (d:Domain {hostname: $target})-[:HAS_CERTIFICATE]->(c:Certificate) RETURN count(c) AS cert_count", {"target": target})
        memories = cypher_read("MATCH (m:Memory) WHERE m.target CONTAINS $target RETURN m ORDER BY m.timestamp DESC LIMIT 200", {"target": target})
        graph_stats = cypher_read("MATCH (n) WHERE n:Domain OR n:Subdomain OR n:IPAddress OR n:Certificate RETURN labels(n)[0] AS type, count(n) AS count")

        # Personality snapshot
        personality = _load_state()

        # ATT&CK mapping
        attack_mapping = attack_framework.map_mission_findings(target)

        # Categorize findings by severity
        findings_by_severity: dict[str, list] = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
        for entry in memories:
            m = entry.get("m", {})
            severity = m.get("severity", "info").lower()
            if severity in findings_by_severity:
                findings_by_severity[severity].append({
                    "type": m.get("memory_type", ""),
                    "content": m.get("content", ""),
                    "timestamp": str(m.get("timestamp", "")),
                })

        # Build report sections
        report = {
            "id": report_id,
            "target": target,
            "generated_at": timestamp,
            "generator": "PITBULL v0.6.0",
            "personality_snapshot": {
                "openness": personality.openness,
                "conscientiousness": personality.conscientiousness,
                "extraversion": personality.extraversion,
                "agreeableness": personality.agreeableness,
                "neuroticism": personality.neuroticism,
                "mood": personality.mood,
                "missions_completed": personality.missions_completed,
                "findings_total": personality.findings_total,
            },
            "executive_summary": self._generate_exec_summary(target, stats, ips, certs, memories, attack_mapping),
            "statistics": {
                "subdomains": stats[0]["sub_count"] if stats else 0,
                "ip_addresses": ips[0].get("ips", []) if ips else [],
                "certificates": certs[0]["cert_count"] if certs else 0,
                "total_memories": len(memories),
                "graph_nodes": {r.get("type", ""): r.get("count", 0) for r in graph_stats},
            },
            "findings_by_severity": findings_by_severity,
            "findings_count": {
                "critical": len(findings_by_severity["critical"]),
                "high": len(findings_by_severity["high"]),
                "medium": len(findings_by_severity["medium"]),
                "low": len(findings_by_severity["low"]),
                "info": len(findings_by_severity["info"]),
            },
            "attack_mapping": attack_mapping,
            "academic_citations": self._get_citations(),
            "methodology": self._get_methodology(),
            "disclaimer": "This report was generated by PITBULL, an autonomous digital explorer. All data was collected through passive and active reconnaissance techniques. No exploitation was performed. Findings should be verified before action.",
        }

        # Store report
        from app.core.database import cypher_write
        cypher_write(
            "CREATE (m:Memory {id: $id}) "
            "SET m.memory_type = 'procedural', m.content = $content, "
            "m.target = $target, m.severity = 'info', m.timestamp = datetime(), "
            "m.report_id = $report_id",
            {
                "id": str(uuid.uuid4())[:12],
                "content": f"Generated exploration report for {target} — {report['findings_count']['critical']} critical, {report['findings_count']['high']} high, {report['findings_count']['medium']} medium",
                "target": target,
                "report_id": report_id,
            },
        )

        return report

    def _generate_exec_summary(self, target, stats, ips, certs, memories, attack_mapping) -> str:
        sub_count = stats[0]["sub_count"] if stats else 0
        ip_list = ips[0].get("ips", []) if ips else []
        cert_count = certs[0]["cert_count"] if certs else 0
        mem_count = len(memories)

        critical = sum(1 for m in memories if m.get("m", {}).get("severity", "").lower() == "critical")
        high = sum(1 for m in memories if m.get("m", {}).get("severity", "").lower() == "high")

        return (f"PITBULL conducted an autonomous exploration of {target} using multiple reconnaissance techniques. "
                f"The exploration discovered {sub_count} subdomains, {len(ip_list)} IP addresses, and {cert_count} certificates. "
                f"A total of {mem_count} findings were recorded, including {critical} critical and {high} high-severity items. "
                f"Findings were mapped to {attack_mapping.get('techniques_mapped', 0)} MITRE ATT&CK techniques "
                f"across {attack_mapping.get('tactic_count', 0)} tactics. "
                f"PITBULL's personality state during this mission: Openness={_load_state().openness:.2f}, "
                f"Neuroticism={_load_state().neuroticism:.2f}, Mood={_load_state().mood}.")

    def _get_citations(self) -> list[dict[str, str]]:
        """Get academic citations relevant to PITBULL's methodology."""
        return [
            {"id": 1, "citation": "Kong, H. et al. (2025). Pentest-R1: Towards Autonomous Penetration Testing Reasoning. arXiv:2508.07382.", "relevance": "Two-stage RL training for pentest reasoning"},
            {"id": 2, "citation": "He, K. et al. (2025). Recon-Act: Self-Evolving Multi-Agent Browser-Use System. arXiv:2509.21072.", "relevance": "Self-evolving tool generation"},
            {"id": 3, "citation": "Liu, H. et al. (2025). Browsing Like Human. ACL 2025.", "relevance": "Dual-process fast/slow thinking"},
            {"id": 4, "citation": "Fei, T. et al. (2026). Memory Beyond Recall. arXiv:2606.09483.", "relevance": "Dual-process cognitive memory"},
            {"id": 5, "citation": "Jiang, H. et al. (2026). SYNAPSE: Spreading Activation in Memory. ACL 2026.", "relevance": "Spreading activation memory graph"},
            {"id": 6, "citation": "Zhang, W. et al. (2026). PersonaAgent. ACL 2026.", "relevance": "Personality-driven agent"},
            {"id": 7, "citation": "Rodriguez Barredo-Valenzuela, A. et al. (2025). Mimir Crawler. IEEE TIFS 2025.", "relevance": "Tor hidden service exploration"},
            {"id": 8, "citation": "MITRE Corporation (2026). ATT&CK Framework v19.", "relevance": "Technique mapping"},
        ]

    def _get_methodology(self) -> list[str]:
        """Get exploration methodology steps."""
        return [
            "DNS Resolution — Resolved target domain to IP addresses using dnspython",
            "Subdomain Enumeration — Discovered subdomains via Certificate Transparency (crt.sh) and DNS brute force",
            "Certificate Transparency — Queried CT logs for historical certificate data",
            "Web Crawling — HTTP-based crawl with technology detection and link extraction",
            "Deep Web Probing — Tested 85+ common paths for admin panels, API docs, exposed configs",
            "WHOIS Lookup — Retrieved domain registration timeline and registrant info",
            "Wayback Machine — Queried CDX API for historical snapshots",
            "GitHub Recon — Searched for leaked secrets and infrastructure references",
            "Shodan Integration — Looked up IP addresses for exposed services (when API key available)",
            "Tor/Darknet Exploration — Classified .onion services with OpSec risk assessment (when applicable)",
            "MITRE ATT&CK Mapping — Mapped findings to relevant ATT&CK techniques",
            "Memory Consolidation — Distilled episodic memories into semantic rules",
            "Personality Evolution — Applied trait adjustments based on mission outcomes",
        ]


report_generator = ReportGenerator()